//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoTPoC.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActivityLog()
        {
            this.LogParams = new HashSet<LogParams>();
        }
    
        public long Id { get; set; }
        public System.DateTime LogTime { get; set; }
        public string LogRequest { get; set; }
        public string SourceIP { get; set; }
        public long FK_DeviceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogParams> LogParams { get; set; }
        public virtual Device Device { get; set; }
    }
}
