//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoTPoC.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallButtonLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CallButtonLog()
        {
            this.CallButtonLogParams = new HashSet<CallButtonLogParams>();
        }
    
        public long Id { get; set; }
        public System.DateTime LogTime { get; set; }
        public string LogRequest { get; set; }
        public string Ip { get; set; }
        public long CallButtonDeviceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallButtonLogParams> CallButtonLogParams { get; set; }
        public virtual CallButtonDevice CallButtonDevice { get; set; }
    }
}
