//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoTPoC.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IoTPoCDBEntities : DbContext
    {
        public IoTPoCDBEntities()
            : base("name=IoTPoCDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CallButtonLog> CallButtonLogSet { get; set; }
        public virtual DbSet<CallButtonLogParams> CallButtonLogParamsSet { get; set; }
        public virtual DbSet<CallButtonDevice> CallButtonDeviceSet { get; set; }
    }
}
