//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoTPoC.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogParams
    {
        public long Id { get; set; }
        public string Param { get; set; }
        public string Value { get; set; }
        public long FK_LogId { get; set; }
    
        public virtual ActivityLog ActivityLog { get; set; }
    }
}
